CREATE DATABASE IF NOT EXISTS WP_DATABASE;
CREATE USER IF NOT EXISTS 'WP_ADM'@'%' IDENTIFIED BY 'WP_PWD_ADM';
GRANT ALL ON *.* TO 'WP_ADM'@'%' IDENTIFIED BY 'WP_PWD_ADM' WITH GRANT OPTION;
CREATE USER IF NOT EXISTS 'WP_USER'@'%' IDENTIFIED BY 'WP_PWD_USER';
GRANT ALL ON WP_DATABASE.* TO 'WP_USER'@'%' IDENTIFIED BY 'WP_PWD_USER' WITH GRANT OPTION;
DELETE FROM mysql.user WHERE User='root';
FLUSH PRIVILEGES;
exit
